# Generated by Django 6.0.5 on 2026-05-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award_Miles_Package',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('harga_paket', models.FloatField()),
                ('jumlah_award_miles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bandara',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('', 'No Salutation')], max_length=10),
        ),
        migrations.CreateModel(
            name='Claim_Missing_Miles',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal_penerbangan', models.DateField()),
                ('flight_number', models.CharField(max_length=10)),
                ('nomor_tiket', models.CharField(max_length=20)),
                ('kelas_kabin', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20)),
                ('pnr', models.CharField(max_length=10)),
                ('status_penerimaan', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('bandara_asal', models.ForeignKey(db_column='bandara_asal', on_delete=django.db.models.deletion.CASCADE, related_name='bandara_asal_set', to='api.bandara')),
                ('bandara_tujuan', models.ForeignKey(db_column='bandara_tujuan', on_delete=django.db.models.deletion.CASCADE, related_name='bandara_tujuan_set', to='api.bandara')),
                ('email_member', models.ForeignKey(db_column='email_member', on_delete=django.db.models.deletion.CASCADE, to='api.member')),
                ('email_staf', models.ForeignKey(db_column='email_staf', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staf')),
                ('maskapai', models.ForeignKey(db_column='maskapai', on_delete=django.db.models.deletion.CASCADE, to='api.maskapai')),
            ],
        ),
        migrations.CreateModel(
            name='Hadiah',
            fields=[
                ('kode_hadiah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('valid_start_date', models.DateField()),
                ('program_end', models.DateField()),
                ('id_penyedia', models.ForeignKey(db_column='id_penyedia', on_delete=django.db.models.deletion.CASCADE, to='api.penyedia')),
            ],
        ),
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('nomor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_habis', models.DateField()),
                ('tanggal_terbit', models.DateField()),
                ('negara_penerbit', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Paspor', 'Paspor'), ('KTP', 'KTP'), ('SIM', 'SIM')], max_length=30)),
                ('email_member', models.ForeignKey(db_column='email_member', on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Member_Award_Miles_Package',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('pk', models.CompositePrimaryKey('id_award_miles_package', 'email_member', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('email_member', models.ForeignKey(db_column='email_member', on_delete=django.db.models.deletion.CASCADE, to='api.member')),
                ('id_award_miles_package', models.ForeignKey(db_column='id_award_miles_package', on_delete=django.db.models.deletion.CASCADE, to='api.award_miles_package')),
            ],
        ),
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('email_mitra', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_mitra', models.CharField(max_length=100)),
                ('tanggal_kerja_sama', models.DateField()),
                ('id_penyedia', models.OneToOneField(db_column='id_penyedia', on_delete=django.db.models.deletion.CASCADE, to='api.penyedia')),
            ],
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('pk', models.CompositePrimaryKey('email_member', 'kode_hadiah', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('email_member', models.ForeignKey(db_column='email_member', on_delete=django.db.models.deletion.CASCADE, to='api.member')),
                ('kode_hadiah', models.ForeignKey(db_column='kode_hadiah', on_delete=django.db.models.deletion.CASCADE, to='api.hadiah')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('jumlah', models.IntegerField()),
                ('catatan', models.CharField(max_length=255)),
                ('pk', models.CompositePrimaryKey('email_member_1', 'email_member_2', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('email_member_1', models.ForeignKey(db_column='email_member_1', on_delete=django.db.models.deletion.CASCADE, related_name='trf_sender_set', to='api.member')),
                ('email_member_2', models.ForeignKey(db_column='email_member_2', on_delete=django.db.models.deletion.CASCADE, related_name='trf_receiver_set', to='api.member')),
            ],
        ),
    ]
